// <auto-generated />
using System;
using Chatty.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chatty.Api.Migrations
{
    [DbContext(typeof(ChatDbContext))]
    [Migration("20230322111103_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Chatty.Api.Models.Chat", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id", "userId");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("Chatty.Api.Models.Message", b =>
                {
                    b.Property<int>("chatId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime(6)");

                    b.HasKey("chatId", "Id", "userId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Chatty.Api.Models.User", b =>
                {
                    b.Property<int>("chatId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("registrationDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("chatId", "Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Chatty.Api.Models.UserChatList", b =>
                {
                    b.Property<int>("chatId")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("chatId", "userId");

                    b.ToTable("UserChatLists");
                });
#pragma warning restore 612, 618
        }
    }
}
