FROM mcr.microsoft.com/dotnet/aspnet:6.0 as base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY . /src
ENV IsDevelopment = true
RUN ls
RUN dotnet build "Chatty.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Chatty.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Chatty.Api.dll"]